seed: 42
device: auto
data:
  train_root: data/train
  val_root: data/val
  img_size: 224
  batch_size: 32
model:
  backbone: reynoldsnet_tiny
  attention: true
  num_classes: 4
optim:
  lr: 3e-4
  weight_decay: 1e-4
  epochs: 20
  warmup_epochs: 1
  label_smoothing: 0.05
train:
  mixup: 0.0
  cutmix: 0.0
  dropout: 0.3
eval:
  mc_dropout_passes: 20
  topk: 3
save:
  ckpt_dir: models
  best_metric: accuracy
